USE swgemu;

CREATE TABLE IF NOT EXISTS discord_join (id INT(10) AUTO_INCREMENT PRIMARY KEY, username VARCHAR(64) NOT NULL, timestamp BIGINT(11) UNSIGNED NOT NULL);
CREATE TABLE IF NOT EXISTS discord_leave (id INT(10) AUTO_INCREMENT PRIMARY KEY, username VARCHAR(64) NOT NULL, roles TEXT, timestamp BIGINT(11) UNSIGNED NOT NULL);
CREATE TABLE IF NOT EXISTS discord_verified (id INT(10) AUTO_INCREMENT PRIMARY KEY, tag VARCHAR(64) NOT NULL, account_id INT(10) unsigned, timestamp BIGINT(11) UNSIGNED NOT NULL);